### ISSUE TITLE
DRK 2-hour drain is adding to parse total when it shouldn't

### ISSUE THREAD

**Issue by 9001-Sols** [WinterSolstice8/parse#1]
![image](https://github.com/WinterSolstice8/parse/assets/43099213/a7f6a94d-7a4a-4315-a677-6b0dd007f335)

`Soul Eater` drain does not add additional damage to attacks and shouldn't be included in the parse

**Comment by WinterSolstice8** [comment]
may be unfixable without a real hack job of tracking Blood Weapon, the add effect message for blood weapon is the same as stuff that (allegedly) actually drains like bloody sword/rapier and bloody bolts

i will need to investigate further to verify that

**Comment by Reiginsei** [comment]
If tracking Blood Weapon would be too much of an issue, how about a toggle to disable the tracking of the Additional Effect: Drain? 

Kparser (and I'd assume Scoreboard for windower) seems to disable the additional effect drains from counting and Deeps just throws its hands up and is outright broken during Blood Weapon.

A toggle would allow you to keep the functionality for the bloody bolts and other weapons, while allowing proper tracking during DRK 2hr.

**Comment by WinterSolstice8** [comment]
Turns out all add effect drains do not appear to actually add damage from some retail testing

https://github.com/WinterSolstice8/parse/releases/tag/v0.984
