### ISSUE TITLE
Monk defensive traits aren't tracked.

### ISSUE THREAD

**Issue by gdiShun** [WinterSolstice8/parse#4]
Guard does not seem to be tracked at all currently. Seems to be treated as a normal hit.

Counter rate is not tracked directly, but is tracked indirectly through being treated as an Evade. Counter damage also does not seem to be tracked.

**Comment by WinterSolstice8** [comment]
I added defensive tracking of guard/counter in v0.985

**Comment by WinterSolstice8** [comment]
Fixed with v0.986, please report if the percentages aren't accurate
